service: better-dynamodb-scaling

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cloudwatch:PutMetricAlarm
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:BatchWriteItem
        - dynamodb:PutItem
      Resource: "*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:us-east-1:*:function:${self:service}-${opt:stage, self:provider.stage}-*"

functions:
  generate_linear_load:
    handler: functions/generate_linear_load.handler
    timeout: 10

  change_cw_alarms:
    handler: functions/change_cw_alarm.handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - aws.monitoring
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - monitoring.amazonaws.com
              eventName:
                - PutMetricAlarm